name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-23.11
    - run: mkdir build
    - name: Build
      run: nix-shell --run "cmake -S . -B ./build && cd build && make"
    - uses: actions/upload-artifact@v4
      with:
        name: Build
        path: build/block.zip
