name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-23.11
    - name: use-nix-shell-action
      uses: rrbutani/use-nix-shell-action@v1.1.0
    - run: nix-shell
    - run: mkdir build
    - name: Build
      run: cmake --build build
    - name: Archive
      run: make artifact
    - uses: actions/upload-artifact@v4
      with:
        name: Build
        path: build/block.zip
