name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:23.11
    - run: nix-shell --run make artifact
    - uses: actions/upload-artifact@v4
      with:
        name: Build
        path: block.zip
